version: "3.7"
   
services:
  emacs:
    image: nakkaya/emacs:latest
    network_mode: "host"
    command: emacs
    restart: "no"
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - $HOME/.Xauthority:/home/nakkaya/.Xauthority:rw
      - $HOME:/storage
